---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-one  
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aks-helloworld-one

---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-two  
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aks-helloworld-two    